# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: ubuntu:22.04
 
# Developers are expected to push an update to this file
# for example by updating the version to release
# to trigger signature
variables:
  RELEASED_VERSION: "0.3.29"
  UNSIGNED_TARFILE: bioimageit_macOS_arm64_v0.3.29.app.tar.gz
  UNSIGNED_TARFILE_URL: "https://gitlab-int.inria.fr/api/v4/projects/474/packages/generic/1/v1.0/bioimageit_macOS_arm64_v0.3.29.app.tar.gz"

.reference_script: &reference_script
  - export DEBIAN_FRONTEND="noninteractive"
  - apt update
  - apt -y install --no-install-recommends curl ca-certificates xz-utils python3 python3-pip
  - python3 -m pip install --user --extra-index-url https://si-repository.inria.fr/ci sign_server
  # fetch the app to sign
  - "curl --fail-with-body --output $UNSIGNED_TARFILE --header \"JOB-TOKEN: $CI_JOB_TOKEN\" $UNSIGNED_TARFILE_URL"
  - mkdir artifacts
  - python3 sign_and_notarize.py --soft-name BioImage-IT --version-name $RELEASED_VERSION --ci-job-token $CI_JOB_TOKEN --output-dir artifacts
 
stages:
- sign
- build
- test
 
sign:
  stage: sign
  tags:
    - codesign.inria.fr
  script:
    - *reference_script
  artifacts:
    paths:
      - artifacts/*.tgz
  when: manual
  except:
    - dev

job_build_windows:
  stage: build
  tags:
    - windows
  script:
    - cd C:\bioimageit\
    - pixi run --environment package build -y

